### ISSUE TITLE
Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by gimtonic** [dhimasanb/laravel-online-shop#1]
Hi! 
Use
php 7.1
node v8.0.0
npm 5.0.0

After command php artisan db:seed I see :
Seeding: UsersSeeder
Seeding: ProductsSeeder
Seeding: AddressesSeeder

[ErrorException]                         
Invalid argument supplied for foreach()  

Some error in AddressesSeeder.php??

**Comment by dhimasanb** [comment]
Sorry this project hasn't been tested for laravel 5.4 and above. :pray:

**Comment by gimtonic** [comment]
In what version this project will work?

**Comment by vennyyuni27** [comment]
halo mas, saya coba upload project laravel-online-shop ke hosting cpanel tetapi kenapa muncul error 500 ya?
mohon petunjuk ya mas...
thanks...

**Comment by vennyyuni27** [comment]
saya menggunakan php 5.6 di cpanel hosting dan error_log nya berisi
PHP Fatal error:  require(): Failed opening required '/home/notimylk/source-olshop/bootstrap/../source-olshop/vendor/autoload.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/notimylk/source-olshop/bootstrap/autoload.php on line 17

**Comment by dhimasanb** [comment]
> halo mas, saya coba upload project laravel-online-shop ke hosting cpanel tetapi kenapa muncul error 500 ya?
> mohon petunjuk ya mas...
> thanks...

Halo mba, coba pastikan bahwa syarat instalasi laravel terpenuhi seperti membutuhkan Mbstring PHP Extension,dll. Cek jg permission directory dan root directory apakah sudah benar.

> saya menggunakan php 5.6 di cpanel hosting dan error_log nya berisi
> PHP Fatal error: require(): Failed opening required '/home/notimylk/source-olshop/bootstrap/../source-olshop/vendor/autoload.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/notimylk/source-olshop/bootstrap/autoload.php on line 17

Pastikan bahwa sudah ada folder vendor dan permission accessnya sudah benar

**Comment by vennyyuni27** [comment]
> > halo mas, saya coba upload project laravel-online-shop ke hosting cpanel tetapi kenapa muncul error 500 ya?
> > mohon petunjuk ya mas...
> > thanks...
> 
> Halo mba, coba pastikan bahwa syarat instalasi laravel terpenuhi seperti membutuhkan Mbstring PHP Extension,dll. Cek jg permission directory dan root directory apakah sudah benar.
> 
> > saya menggunakan php 5.6 di cpanel hosting dan error_log nya berisi
> > PHP Fatal error: require(): Failed opening required '/home/notimylk/source-olshop/bootstrap/../source-olshop/vendor/autoload.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/notimylk/source-olshop/bootstrap/autoload.php on line 17
> 
> Pastikan bahwa sudah ada folder vendor dan permission accessnya sudah benar

mas dari github yg mas upload blm ada vendor nya trus gmn caranya saya bs menambahkan folder vendor nya ya?

**Comment by dhimasanb** [comment]
> > > halo mas, saya coba upload project laravel-online-shop ke hosting cpanel tetapi kenapa muncul error 500 ya?
> > > mohon petunjuk ya mas...
> > > thanks...
> > 
> > 
> > Halo mba, coba pastikan bahwa syarat instalasi laravel terpenuhi seperti membutuhkan Mbstring PHP Extension,dll. Cek jg permission directory dan root directory apakah sudah benar.
> > > saya menggunakan php 5.6 di cpanel hosting dan error_log nya berisi
> > > PHP Fatal error: require(): Failed opening required '/home/notimylk/source-olshop/bootstrap/../source-olshop/vendor/autoload.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/notimylk/source-olshop/bootstrap/autoload.php on line 17
> > 
> > 
> > Pastikan bahwa sudah ada folder vendor dan permission accessnya sudah benar
> 
> mas dari github yg mas upload blm ada vendor nya trus gmn caranya saya bs menambahkan folder vendor nya ya?

Setelah project di clone, mba harus install project menggunakan composer. Bisa cek lebih lanjut untuk tutorial install laravel mba [Tutorial Install Laravel 5](https://medium.com/@kiddy.xyz/tutorial-install-laravel-5-4-701352c023f3)
